from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        MainWindow.setMinimumSize(QtCore.QSize(400, 600))
        MainWindow.setMaximumSize(QtCore.QSize(400, 600))
        MainWindow.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b0 = QtWidgets.QPushButton(self.centralwidget)
        self.b0.setGeometry(QtCore.QRect(0, 500, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b0.setObjectName("b0")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(0, 400, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(100, 400, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(200, 400, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(0, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(100, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(200, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b6.setObjectName("b6")
        self.b_equal = QtWidgets.QPushButton(self.centralwidget)
        self.b_equal.setGeometry(QtCore.QRect(200, 500, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b_equal.setFont(font)
        self.b_equal.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.b_equal.setObjectName("b_equal")
        self.b7 = QtWidgets.QPushButton(self.centralwidget)
        self.b7.setGeometry(QtCore.QRect(0, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(self.centralwidget)
        self.b8.setGeometry(QtCore.QRect(100, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(self.centralwidget)
        self.b9.setGeometry(QtCore.QRect(200, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);")
        self.b9.setObjectName("b9")
        self.b_ce = QtWidgets.QPushButton(self.centralwidget)
        self.b_ce.setGeometry(QtCore.QRect(0, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b_ce.setFont(font)
        self.b_ce.setStyleSheet("\n"
"background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.b_ce.setObjectName("b_ce")
        self.b_c = QtWidgets.QPushButton(self.centralwidget)
        self.b_c.setGeometry(QtCore.QRect(100, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b_c.setFont(font)
        self.b_c.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.b_c.setObjectName("b_c")
        self.b_modul = QtWidgets.QPushButton(self.centralwidget)
        self.b_modul.setGeometry(QtCore.QRect(200, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b_modul.setFont(font)
        self.b_modul.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.b_modul.setObjectName("b_modul")
        self.b_plus = QtWidgets.QPushButton(self.centralwidget)
        self.b_plus.setGeometry(QtCore.QRect(300, 400, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b_plus.setFont(font)
        self.b_plus.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.b_plus.setObjectName("b_plus")
        self.b_minus = QtWidgets.QPushButton(self.centralwidget)
        self.b_minus.setGeometry(QtCore.QRect(300, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b_minus.setFont(font)
        self.b_minus.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.b_minus.setObjectName("b_minus")
        self.b_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.b_multiply.setGeometry(QtCore.QRect(300, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b_multiply.setFont(font)
        self.b_multiply.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.b_multiply.setObjectName("b_multiply")
        self.b_divide = QtWidgets.QPushButton(self.centralwidget)
        self.b_divide.setGeometry(QtCore.QRect(300, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.b_divide.setFont(font)
        self.b_divide.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.b_divide.setObjectName("b_divide")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(40)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setMargin(15)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_funksion()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b_equal.setText(_translate("MainWindow", "="))
        self.b7.setText(_translate("MainWindow", "7"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b_ce.setText(_translate("MainWindow", "Ce"))
        self.b_c.setText(_translate("MainWindow", "C"))
        self.b_modul.setText(_translate("MainWindow", "%"))
        self.b_plus.setText(_translate("MainWindow", "+"))
        self.b_minus.setText(_translate("MainWindow", "-"))
        self.b_multiply.setText(_translate("MainWindow", "*"))
        self.b_divide.setText(_translate("MainWindow", "/"))
        self.label.setText(_translate("MainWindow", "0"))

    def add_funksion(self):
        self.b0.clicked.connect(lambda: self.write_number(self.b0.text())) 
        self.b1.clicked.connect(lambda: self.write_number(self.b1.text()))
        self.b2.clicked.connect(lambda: self.write_number(self.b2.text()))
        self.b3.clicked.connect(lambda: self.write_number(self.b3.text()))
        self.b4.clicked.connect(lambda: self.write_number(self.b4.text()))
        self.b5.clicked.connect(lambda: self.write_number(self.b5.text()))
        self.b6.clicked.connect(lambda: self.write_number(self.b6.text()))
        self.b7.clicked.connect(lambda: self.write_number(self.b7.text()))
        self.b8.clicked.connect(lambda: self.write_number(self.b8.text()))
        self.b9.clicked.connect(lambda: self.write_number(self.b9.text()))
        self.b_modul.clicked.connect(lambda: self.write_number(self.b_modul.text()))
        self.b_plus.clicked.connect(lambda: self.write_number(self.b_plus.text()))
        self.b_minus.clicked.connect(lambda: self.write_number(self.b_minus.text()))
        self.b_multiply.clicked.connect(lambda: self.write_number(self.b_multiply.text()))
        self.b_divide.clicked.connect(lambda: self.write_number(self.b_divide.text()))
        self.b_equal.clicked.connect(self.results)
        self.b_c.clicked.connect(self.delete_all)
        self.b_ce.clicked.connect(self.delete)


    def write_number(self, number):
        if(self.label.text() == "0"):
            self.label.setText(number)
        else:
            self.label.setText(self.label.text() + number)

    def results(self):
        self.label.setText(str(eval(self.label.text())))

    def delete(self):
        self.label.setText(self.label.text()[:len(self.label.text()) -1])

    def delete_all(self):
        self.label.setText("0")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
